services:
  web:
    build: .
    entrypoint: /home/app/web/entrypoint.sh
    expose:
      - 8000
    volumes:
      - .:/home/app/web/
      - ./static/:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  celery:
    build: .
    entrypoint: /home/app/web/celery_entrypoint.sh
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
    restart: always

  celery_beat:
    build: .
    entrypoint: /home/app/web/celery_beat_entrypoint.sh
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
    restart: always

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  nginx:
    build: nginx
    volumes:
      - media_volume:/home/app/web/media
      - ./static/:/home/app/web/static
      - ./.well-known/:/home/app/web/.well-known
    ports:
      - 8001:80
    depends_on:
      - web
    env_file:
      - .env
    restart: always
  
  redis:
    image: redis:7-alpine
    restart: always

  flower:
    image: mher/flower:0.9.5
    command: [ 'flower', '--broker=redis://redis:6379', '--port=5555' ]
    ports:
      - 5555:5555

volumes:
  postgres_volume:
  media_volume:
